# Generated by Django 4.2.9 on 2026-03-17 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('want_to_watch', 'Хочу посмотреть'), ('watching', 'Смотрю'), ('watched', 'Посмотрел')], default='want_to_watch', max_length=20)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlists', to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Список просмотра',
                'verbose_name_plural': 'Списки просмотра',
                'ordering': ['-added_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='watchlist_w_user_id_ee22c6_idx')],
                'unique_together': {('user', 'movie')},
            },
        ),
    ]
